# Configuración de KickChat

# CAMBIA ESTO POR TU NOMBRE REAL
streamer_name: "tunombredeusuario"

# DÉJALOS EN 0 PARA QUE EL PLUGIN LOS BUSQUE
chatroom_id: 0
channel_id: 0

# --- CONFIGURACIÓN DE BOTS Y FILTROS ---
bot_settings:
  filter_enabled: true
  at_name_color: "&b" # Color Aqua para bots
  
  blocked_list:
    - '@Kicklet' # Bots silenciados por defecto

  known_bots:
    - '@Kicklet'
    - '@BotRix'
    - '@Nightbot'
    - '@StreamElements'

# --- MODERACIÓN Y CONTROL ---
chat_enabled: true

muted_users: [] # Lista vacía al principio